Failure # 1 (occurred at 2024-09-02_10-11-26)
The actor died because of an error raised in its creation task, [36mray::IMPALA.__init__()[39m (pid=3848559, ip=143.248.233.21, actor_id=1a80ae2eafeb6caa434e01a201000000, repr=IMPALA)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 502, in __init__
    config.validate()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 385, in validate
    super().validate()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 837, in validate
    self._validate_evaluation_settings()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 4074, in _validate_evaluation_settings
    raise ValueError(
ValueError: `evaluation_parallel_to_training` can only be done if `evaluation_num_env_runners` > 0! Try setting `config.evaluation_parallel_to_training` to False.
